
import "./globals.css";
import Navbar from "./layer/Navbar";
import ProfileCard from "./components/ProfileCard";
import Container from "./components/Container";
import Background from "./components/Background";
import ServicesOffered from "./components/ServicesOffered";
import Footer from "./layer/Footer";
import { Poppins } from "next/font/google";
import MouseMove from "./components/MouseMove";
import BackgroundShape from "./components/BackgroundShape";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"], 
});

export const metadata = {
  title: "CEO-- Portfolio",
  description: "Generated by Havtic",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" >
      <body className="dark:bg-black bg-gradient-to-r font-poppins from-[#9e828260] via-[#96817123] to-[#8089bc2d] dark:from-[#170808] dark:via-[#1f1f1f] dark:to-[#0a1145bb]">
        <Navbar />
        <Container className="gap-[24px] flex mt-[42px] z-[99]">
          <ProfileCard />
          {children}
        </Container>
        <ServicesOffered />
        <Footer />
        <Background className={" -z-10 top-[-20%] left-[-15%] w-[1000px]"} />
        <Background
          className={" -z-10 bottom-[-40%] right-[-15%] w-[1000px]"}
        />
        <MouseMove/>
        <BackgroundShape/>
      </body>
    </html>
  );
}
